import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Signature Artisanal Crochet Tote Bag",
    description: "Handcrafted with premium sage green and natural cream cotton yarn. Features sturdy wooden handles, soft inner lining, and spacious interior perfect for everyday elegance.",
    price: 1899,
    discountPrice: 1499,
    imageUrl: "/assets/images/crochet-tote-bag.png",
    category: "Bags & Totes",
    isBestSeller: true,
    discountTag: "20% OFF",
    stock: 15,
    isActive: true,
    createdAt: Date.now() - 100000,
    updatedAt: Date.now() - 50000,
  },
  {
    id: "prod-2",
    title: "Chunky Knit Oversized Cardigan",
    description: "Ultra-cozy hand-knitted cardigan in warm amber mustard wool. Breathable, super soft texture with wooden button detailing and relaxed fit.",
    price: 3499,
    discountPrice: 2999,
    imageUrl: "/assets/images/chunky-knit-cardigan.png",
    category: "Apparel",
    isBestSeller: true,
    discountTag: "HOT",
    stock: 8,
    isActive: true,
    createdAt: Date.now() - 90000,
    updatedAt: Date.now() - 40000,
  },
  {
    id: "prod-3",
    title: "Handcrafted Soft Plush Teddy Bear",
    description: "Adorable hand-crocheted plush bear made from hypoallergenic, organic oatmeal wool. Perfectly soft for children and plush collectors alike.",
    price: 1199,
    discountPrice: 899,
    imageUrl: "/assets/images/handcrafted-plush-toy.png",
    category: "Toys & Plushies",
    isBestSeller: false,
    discountTag: "Popular",
    stock: 20,
    isActive: true,
    createdAt: Date.now() - 80000,
    updatedAt: Date.now() - 30000,
  },
  {
    id: "prod-4",
    title: "Vintage Terracotta Crochet Bucket Hat",
    description: "Stylish retro bucket hat hand-woven with earthy terracotta and natural cream pattern. Lightweight, breathable, and sun-protective.",
    price: 999,
    discountPrice: 799,
    imageUrl: "/assets/images/crochet-bucket-hat.png",
    category: "Accessories",
    isBestSeller: false,
    discountTag: "NEW",
    stock: 12,
    isActive: true,
    createdAt: Date.now() - 70000,
    updatedAt: Date.now() - 20000,
  },
  {
    id: "prod-5",
    title: "Luxury Cable Knit Throw Blanket",
    description: "Plush, heavy-weight cable knit throw blanket in ivory natural alpaca wool blend. Adds cozy texture and warmth to any modern living room or bedroom.",
    price: 3999,
    discountPrice: 3499,
    imageUrl: "/assets/images/luxury-knit-blanket.png",
    category: "Home & Decor",
    isBestSeller: true,
    discountTag: "PREMIUM",
    stock: 6,
    isActive: true,
    createdAt: Date.now() - 60000,
    updatedAt: Date.now() - 10000,
  }
];
